### ISSUE TITLE
adding images

### ISSUE THREAD

**Issue by ruzkas** [connor-baer/summer#14]
When adding a new image to the _images folder, is there a certain task I need to run for the image versions (small, large) to be created in assets? Thanks in advance.

**Comment by connor-baer** [comment]
Have a look at the `package.json` file to see the [available scripts](https://github.com/connor-baer/summer/blob/master/package.json#L6-L11). `yarn start` and `yarn build` both run `gulp` tasks that generate optimized images (see https://github.com/connor-baer/summer/tree/master/gulpfile.js/tasks).

**Comment by ruzkas** [comment]
Thanks, running 'yarn build/yarn start' worked, I had to prepend it with bundle exec though. 
Another issue I had when I tried to run the site on the local host for the first time was that the server address generated by 'yarn start' did not show the styles and the links were broken. I was able to get the fully functional website on the local server by running bundle exec jekyll serve. Is there anything I'm doing wrong?

**Comment by connor-baer** [comment]
`bundle exec` is a Ruby command, mixing it with `yarn` scripts sounds...wrong. Nice if it works though 🤷‍♂️👍

You might have to change some values in the [`_config.yml`](https://github.com/connor-baer/summer/blob/master/_config.yml#L43) file, probably the `baseUrl` is causing issues. 

Please note that **this theme is no longer actively maintained**. I usually don't respond to support requests, for further questions, please familiarize yourself with the source code or refer to the [Jekyll](https://jekyllrb.com/) documentation.

**Comment by ruzkas** [comment]
Got it! Thanks for getting back to me!
