### ISSUE TITLE
Dark is not working?

### ISSUE THREAD

**Issue by maggenti** [connor-baer/summer#9]
What am I doing wrong: Switching "dark_theme:" to True does nothing, so how do you turn on dark mode? Do I need to rename "styles-dark.css" and "styles-dark.css.map" to "styles.css" and "styles.css.map"  This seems like it should not be an issue and yet it is. I have worked on this a while with no solution. Could you please let me know what I am doing wrong?
Thanks for any help

**Comment by connor-baer** [comment]
Hi @maggenti! It looks like the switch between the light and dark theme didn't happen. I've just [committed a fix](https://github.com/connor-baer/summer/commit/a360b0a8ac361b9d6d40bcd018984d1b5977bba7). Let me know if that solves your issue.

**Comment by maggenti** [comment]
I really appreciate you looking into this, but now I do not seem to have
any css loading at all? The page is without any css of any kind? And it is
still white?

**Comment by maggenti** [comment]
Ok, I downloaded the entire thing again, and it worked just fine. I must
have messed up something thanks very much. I can close it or you can thanks
so very much for your help. Have a great day
